# Generated by Django 2.1.3 on 2018-12-01 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_tesouro', models.ImageField(upload_to='imgs', verbose_name='Imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorte', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
